services:
  api:
    image: epargneargents-api:latest
    container_name: saving-money-generator

    restart: unless-stopped

    networks:
      - proxy

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9384

    volumes:
      - /mnt/nvme/epargneargents/csv_output:/app/GeneratedCsvOutputFolder

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9384/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP
      - "traefik.http.routers.epargneargents-http.rule=Host(`saving-money-generator.my-pi.lan`)"
      - "traefik.http.routers.epargneargents-http.entrypoints=web"
      - "traefik.http.routers.epargneargents-http.middlewares=chain-http@file"

      # HTTPS
      - "traefik.http.routers.epargneargents-https.rule=Host(`saving-money-generator.my-pi.lan`)"
      - "traefik.http.routers.epargneargents-https.entrypoints=websecure"
      - "traefik.http.routers.epargneargents-https.tls=true"
      - "traefik.http.routers.epargneargents-https.middlewares=chain-https@file"

      # Internal ASP.NET port
      - "traefik.http.services.epargneargents.loadbalancer.server.port=9384"

      # Optional metadata
      - "com.example.app=epargneargents"
      - "com.example.version=1.0.0"

networks:
  proxy:
    external: true
